version: '3.8'

services:
  backvonia:
    build:
      context: .
      dockerfile: Dockerfile
    image: backvonia:latest
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./.env:/app/.env:ro

  migrate:
    image: backvonia:latest
    volumes:
      - ./config.yaml:/app/config.yaml:ro
