[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
uuid = { version = "1", features = ["v4", "serde"] }
time = { version = "0.3", features = ["serde", "macros"] }
